# Never copy this file from other mods, always use https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod
# Filename must be the same as tp2 basename, placed in the same folder where
# .tp2 file is located, use UTF8 (without BOM) encoding, everything is optional

# ini section header is required to avoid false detection
[Metadata]

# Full name of the mod, without the list of supported games, without the version number, without 'Mod'
Name = Geomantic Sorcerer Kit

# Author name or nick, don't use an email address
Author = Caedwyr

# Short description of the mod, main goals, features etc
Description = The Geomantic Sorcerer Kit is strongly based on the Druidic Sorcerer Kit by Constant Gaw, and resurrected by hlidskialf and loosely based on the Geomancer prestige class from the AD&D 3rd Edition Masters of the Wild manual. The kit combines the sorcerer's spellcasting methods and spells with additional druidic spells and abilities and features its own unique tiered HLA progression and custom spells.

# Web address of mod readme file (filename is case-sensitive!), comma-separated list. You can link to txt, md, html, pdf etc.
Readme = https://gibberlings3.github.io/Documentation/readmes/readme-druidsor.html

# Web address of mod dedicated forum or forum thread 
Forum = https://www.gibberlings3.net/forum/28-miscellaneous-released-mods/

# Web address of mod personal Homepage, no need to duplicate with a mod dedicated forum
Homepage = https://www.gibberlings3.net/mods/kits/geomantic/

# If you use GitHub.com, simply use https://github.com/AccountOrOrgName/RepositoryName (omit /releases)
# read more about Delta Updates https://github.com/ALIENQuake/ProjectInfinity/wiki/Delta-Updates-for-mods-hosted-at-Github
Download = https://github.com/Gibberlings3/Geomantic_Sorcerer

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order, use mod ID as tp2 name without file extension and `setup-` prefix

# This mod must be installed *before* those ModID listed below, comma-separated list:
Before = cdtweaks, stratagems

# This mod must be installed *after* those ModID listed below, comma-separated list:
After = eefixpack, bg2fixpack